version: '3.7'

services:
  web:
    container_name: php7-apache2
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  db:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nova_senha
      MYSQL_DATABASE: home_security
      MYSQL_USER: root
      MYSQL_PASSWORD: nova_senha
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.1
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: nova_senha
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local